on:   
  discussion:
    types: [created, answered]
  discussion_comment:
    types: [created]   
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: BP-Discussions
        SLACK_CHANNEL: gordy-test
        MSG_MINIMAL: true
        SLACK_TITLE: New Discussions Update!
        MESSAGE: ':rocket:'
        
